packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - '@heroui/shared-utils'
  - esbuild
  - msw
  - onnxruntime-node
  - protobufjs
  - sharp
  - simple-git-hooks
  - workerd

catalog:
  react: ^19.1.0
  'react-dom': ^19.1.0
  '@types/react': ^19.1.3
  '@types/react-dom': ^19.1.3
