onlyBuiltDependencies:
  - '@depot/cli'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - msw
  - onnxruntime-node
  - protobufjs
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - workerd
