packages:
  - "apps/*"
  - "packages/*"

publicHoistPattern:
  - "*@heroui/*"

onlyBuiltDependencies:
  - "@heroui/shared-utils"
  - esbuild
  - msw
  - onnxruntime-node
  - protobufjs
  - sharp
  - simple-git-hooks
  - workerd
