packages:
  - apps/*
  - packages/*
catalog:
  react: ^19.1.0
  react-dom: ^19.1.0
  '@types/react': ^19.1.3
  '@types/react-dom': ^19.1.3
  next: ^15.3.2
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
  - msw
  - onnxruntime-node
  - protobufjs
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - workerd
